### ISSUE TITLE
multi-token word concatenation doesn't work for less common unicode symbols.

### ISSUE THREAD

**Issue by RutgerEttes** [byungdoh/attn_dist#2]
Hi, while running main.py on some data the code seemed to be breaking due to the conversion to and from latin-1 encoding for multitoken words because some of the tokens were not compatible with latin-1.

I managed to avoid this by using `tokenizer.convert_tokens_to_string()`  instead of this process using latin-1.

to accomodate this change, I also change line 141 to:
```
curr_word = []
```
and lines 189-197 to

```
curr_word += [toks[i]]
curr_word_str = tokenizer.convert_tokens_to_string(curr_word)

if words[curr_word_ix] == curr_word_str.strip():
    print(curr_word_str + " " + " ".join([str(val) for val in curr_word_vals]))
    curr_word_vals = [0] * 12
    curr_word = []
    curr_word_ix += 1
```

Which solved my issue.

**Comment by byungdoh** [comment]
I think that's a great solution! Thanks for taking the time to bring up this suggestion.
